<a href="https://colab.research.google.com/github/Shiva-15711/NLP/blob/main/NLP_Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing nltk for tokenization

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

Tokenizing given data into sentences

In [ ]:
tokenizer = nltk.data.load('tokenizers/punkt/english.pickle')

paragraph_data = "A paragraph is a series of sentences that are organized and coherent, and are all related to a single topic. Almost every piece of writing you do that is longer than a few sentences should be organized into paragraphs. This is because paragraphs show a reader where the subdivisions of an essay begin and end, and thus help the reader see the organization of the essay and grasp its main points. Paragraphs can contain many different kinds of information. A paragraph could contain a series of brief examples or a single long illustration of a general point. It might describe a place, character, or process; narrate a series of events; compare or contrast two or more things; classify items into categories; or describe causes and effects. Regardless of the kind of information they contain, all paragraphs share certain characteristics. One of the most important of these is a topic sentence."
sentences = tokenizer.tokenize(paragraph_data)
print(sentences) #Printing the tokenized sentences

['A paragraph is a series of sentences that are organized and coherent, and are all related to a single topic.', 'Almost every piece of writing you do that is longer than a few sentences should be organized into paragraphs.', 'This is because paragraphs show a reader where the subdivisions of an essay begin and end, and thus help the reader see the organization of the essay and grasp its main points.', 'Paragraphs can contain many different kinds of information.', 'A paragraph could contain a series of brief examples or a single long illustration of a general point.', 'It might describe a place, character, or process; narrate a series of events; compare or contrast two or more things; classify items into categories; or describe causes and effects.', 'Regardless of the kind of information they contain, all paragraphs share certain characteristics.', 'One of the most important of these is a topic sentence.']


Word2vec

In [ ]:
import tensorflow_hub as hub
word_2_vector = hub.KerasLayer("https://tfhub.dev/google/Wiki-words-500/2")
print(word_2_vector(nltk.tokenize.word_tokenize(paragraph_data)))

tf.Tensor(
[[ 0.02491126  0.00975238  0.01899145 ...  0.017017    0.05529895
   0.05232523]
 [ 0.06370258  0.00366226  0.03544654 ... -0.0205587   0.0578904
   0.04946817]
 [ 0.00137178 -0.06974217  0.03241544 ...  0.02436278  0.04049175
   0.05069738]
 ...
 [ 0.03556901 -0.01735091  0.03222941 ... -0.01926812 -0.02928346
   0.02815327]
 [ 0.00760995  0.06446774  0.05579246 ...  0.01736432 -0.05541609
   0.03033571]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]], shape=(167, 500), dtype=float32)


Use

In [ ]:
import tensorflow_hub as hub
use_embeddings = hub.KerasLayer("https://tfhub.dev/google/nnlm-en-dim128/2")
print(use_embeddings(sentences))

tf.Tensor(
[[ 0.58439595  0.03570241  0.07089428 ...  0.16468506  0.01362591
  -0.17049456]
 [ 0.5674903  -0.03022472  0.1454444  ...  0.08465072  0.04284173
   0.03154206]
 [ 0.83034116  0.16388969 -0.03244966 ... -0.20251456  0.12385168
   0.08940062]
 ...
 [ 0.4393374   0.02327458  0.12449444 ...  0.05474888 -0.09519409
   0.00303833]
 [ 0.2909918   0.06627773  0.08403497 ... -0.10017543 -0.11646989
   0.00867226]
 [ 0.5081561  -0.04534546  0.09999924 ...  0.06375446 -0.00892025
  -0.03128232]], shape=(8, 128), dtype=float32)


Elmo

In [ ]:
import tensorflow_hub as hub
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()
elmo_embed=hub.Module("https://tfhub.dev/google/elmo/3",trainable=True)
embeddings=elmo_embed(
    sentences,
    signature="default",
    as_dict=True)["elmo"]


In [ ]:
initial=tf.initialize_all_variables()
sess=tf.Session()
sess.run(initial)
print(sess.run(embeddings[0]))
print("shape=",embeddings[0].shape)

Instructions for updating:
Use `tf.global_variables_initializer` instead.


[[ 0.2928698  -0.1437801  -0.32574037 ... -0.39559233 -0.35758835
  -0.035881  ]
 [-0.5944165   0.0964064   0.50537634 ...  0.22031882  0.26976866
   0.4630725 ]
 [-0.17083272 -0.18744105 -0.27626747 ... -0.675509    0.25390008
   0.654027  ]
 ...
 [-0.02840839 -0.04353214  0.04130162 ...  0.02583166 -0.01429835
  -0.01650421]
 [-0.02840839 -0.04353214  0.04130162 ...  0.02583166 -0.01429835
  -0.01650421]
 [-0.02840839 -0.04353214  0.04130162 ...  0.02583166 -0.01429835
  -0.01650421]]
shape= (32, 1024)


Gp2

In [ ]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 5.3 MB 32.0 MB/s 
     |████████████████████████████████| 163 kB 68.3 MB/s 
     |████████████████████████████████| 7.6 MB 62.7 MB/s 


In [ ]:
import transformers as tr
gptokenizer=tr.GPT2Tokenizer.from_pretrained('gpt2-large')
model=tr.GPT2LMHeadModel.from_pretrained('gpt2-large')

Downloading:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/456k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/666 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/3.25G [00:00<?, ?B/s]

In [ ]:
vector_gp2=gptokenizer.encode(paragraph_data,add_special_tokens=False,return_tensors="pt")
vector_gp2

tensor([[   32,  7322,   318,   257,  2168,   286, 13439,   326,   389,  8389,
           290, 24870,    11,   290,   389,   477,  3519,   284,   257,  2060,
          7243,    13, 16699,   790,  3704,   286,  3597,   345,   466,   326,
           318,  2392,   621,   257,  1178, 13439,   815,   307,  8389,   656,
         23549,    13,   770,   318,   780, 23549,   905,   257,  9173,   810,
           262, 45944,  3279,   286,   281, 14268,  2221,   290,   886,    11,
           290,  4145,  1037,   262,  9173,   766,   262,  4009,   286,   262,
         14268,   290, 13180,   663,  1388,  2173,    13,  2547,  6111,    82,
           460,  3994,   867,  1180,  6982,   286,  1321,    13,   317,  7322,
           714,  3994,   257,  2168,   286,  4506,  6096,   393,   257,  2060,
           890, 20936,   286,   257,  2276,   966,    13,   632,  1244,  6901,
           257,  1295,    11,  2095,    11,   393,  1429,    26,  6664,   378,
           257,  2168,   286,  2995,    26,  8996,  

Sentence bert

In [ ]:
!pip install sentence_transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 85 kB 4.8 MB/s 
     |████████████████████████████████| 1.3 MB 55.5 MB/s 
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125938 sha256=6ee950d2942aea84aff63df2b0dc39f1d729f3a9558e1bd69d811cb849b510d9
  Stored in directory: /root/.cache/pip/wheels/bf/06/fb/d59c1e5bd1dac7f6cf61ec0036cc3a10ab8fecaa6b2c3d3ee9
Successfully built sentence-transformers


In [ ]:
from sentence_transformers import SentenceTransformer
model_sentenceBert = SentenceTransformer('all-MiniLM-L6-v2')

Downloading:   0%|          | 0.00/1.18k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/190 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/612 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/116 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/39.3k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/350 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/13.2k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/349 [00:00<?, ?B/s]

In [ ]:
embedder = model_sentenceBert.encode(sentences)

for sent, embedding in zip(sentences, embedder):
    print("Sentence:", sent)
    print("Embedding:", embedding)
    print("")

Sentence: A paragraph is a series of sentences that are organized and coherent, and are all related to a single topic.
Embedding: [-1.41801266e-02  7.78065110e-03  4.43361178e-02 -2.06465740e-03
  3.15289646e-02  1.17920220e-01 -5.00694998e-02 -5.13058491e-02
  6.12574741e-02  3.83401266e-03  2.46072691e-02  4.37808596e-02
  1.86814461e-02  9.24425572e-03  4.79699671e-02 -2.28641685e-02
  1.08626951e-02 -3.33602689e-02 -7.01994598e-02  2.34185010e-02
  1.07314557e-01  7.35156089e-02  1.65917538e-02  6.15355037e-02
 -2.92453188e-02  8.36600438e-02 -2.86247954e-02 -5.25574908e-02
 -1.74998492e-02  5.74811473e-02 -5.68901771e-04  3.98615897e-02
 -1.29591459e-02  7.39579350e-02 -7.01926136e-03  6.14263192e-02
 -3.18037579e-03  9.95492376e-03  3.50627080e-02 -2.65781861e-02
 -3.49903628e-02 -5.59464283e-03 -5.39436378e-02  4.68934998e-02
  7.01085553e-02 -2.67394092e-02 -4.79424968e-02 -5.18489815e-03
 -7.09361210e-03 -4.07591127e-02 -1.02230020e-01  7.50141889e-02
 -4.75807115e-02  1.05528

Named Entities

In [ ]:
import spacy
from spacy import displacy
from spacy import tokenizer
loader = spacy.load('en_core_web_sm')
doc = loader(paragraph_data)
sent_list = list(doc.sents)
print(sent_list)

[A paragraph is a series of sentences that are organized and coherent, and are all related to a single topic., Almost every piece of writing you do that is longer than a few sentences should be organized into paragraphs., This is because paragraphs show a reader where the subdivisions of an essay begin and end, and thus help the reader see the organization of the essay and grasp its main points., Paragraphs can contain many different kinds of information., A paragraph could contain a series of brief examples or a single long illustration of a general point., It might describe a place, character, or process; narrate a series of events; compare or contrast two or more things; classify items into categories; or describe causes and effects., Regardless of the kind of information they contain, all paragraphs share certain characteristics., One of the most important of these is a topic sentence.]


In [ ]:
entities = [(e.text, e.start_char, e.end_char, e.label_) for e in doc.ents]
print(entities)

displacy.render(doc, style='ent', jupyter=True)

[('two', 657, 660, 'CARDINAL'), ('One', 839, 842, 'CARDINAL')]


Similar sentences using sentence Bert

In [ ]:
from sentence_transformers import SentenceTransformer
sent_bert_model = SentenceTransformer('bert-base-nli-mean-tokens')
import numpy as np

Downloading:   0%|          | 0.00/391 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/190 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/3.95k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/625 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/122 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/438M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/399 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/229 [00:00<?, ?B/s]

In [ ]:
sentence_embeddings = sent_bert_model.encode(sentences)
q1_vec = sent_bert_model.encode(sentences[0])

In [ ]:
def cosine(u, v):
    return np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v))

for sent in sentences:
  sim = cosine(q1_vec, sent_bert_model.encode([sent])[0])
  if sim>0.6:
    print("Sentence - 1 =",sentences[0],"\n \nSentence - 2=", sent, "\n\nSimilarity = \n", sim,end="\n n")

Sentence - 1 = A paragraph is a series of sentences that are organized and coherent, and are all related to a single topic. 
 
Sentence - 2= A paragraph is a series of sentences that are organized and coherent, and are all related to a single topic. 

Similarity = 
 1.0000001
 nSentence - 1 = A paragraph is a series of sentences that are organized and coherent, and are all related to a single topic. 
 
Sentence - 2= Almost every piece of writing you do that is longer than a few sentences should be organized into paragraphs. 

Similarity = 
 0.6477537
 nSentence - 1 = A paragraph is a series of sentences that are organized and coherent, and are all related to a single topic. 
 
Sentence - 2= A paragraph could contain a series of brief examples or a single long illustration of a general point. 

Similarity = 
 0.69272876
 nSentence - 1 = A paragraph is a series of sentences that are organized and coherent, and are all related to a single topic. 
 
Sentence - 2= Regardless of the kind of 

Explain POS Tagging with HMM?


HMM (Hidden Markov Model) is a Stochastic technique for POS tagging. Hidden Markov models are known for their applications to reinforcement learning and temporal pattern recognition such as speech, handwriting, gesture recognition, musical score following, partial discharges, and bioinformatics. POS tags give a large amount of information about a word and its neighbors. They are used as an intermediate step for higher-level NLP tasks such as parsing, semantics analysis, translation, and many more, which makes POS tagging a necessary function for advanced NLP applications.


In [ ]:
import nltk
from nltk import word_tokenize
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


True

In [ ]:
for sents in sentences:
  print(nltk.pos_tag(word_tokenize(sents)))

[('A', 'DT'), ('paragraph', 'NN'), ('is', 'VBZ'), ('a', 'DT'), ('series', 'NN'), ('of', 'IN'), ('sentences', 'NNS'), ('that', 'WDT'), ('are', 'VBP'), ('organized', 'VBN'), ('and', 'CC'), ('coherent', 'NN'), (',', ','), ('and', 'CC'), ('are', 'VBP'), ('all', 'DT'), ('related', 'VBN'), ('to', 'TO'), ('a', 'DT'), ('single', 'JJ'), ('topic', 'NN'), ('.', '.')]
[('Almost', 'RB'), ('every', 'DT'), ('piece', 'NN'), ('of', 'IN'), ('writing', 'VBG'), ('you', 'PRP'), ('do', 'VBP'), ('that', 'DT'), ('is', 'VBZ'), ('longer', 'JJR'), ('than', 'IN'), ('a', 'DT'), ('few', 'JJ'), ('sentences', 'NNS'), ('should', 'MD'), ('be', 'VB'), ('organized', 'VBN'), ('into', 'IN'), ('paragraphs', 'NN'), ('.', '.')]
[('This', 'DT'), ('is', 'VBZ'), ('because', 'IN'), ('paragraphs', 'NN'), ('show', 'VBP'), ('a', 'DT'), ('reader', 'NN'), ('where', 'WRB'), ('the', 'DT'), ('subdivisions', 'NNS'), ('of', 'IN'), ('an', 'DT'), ('essay', 'NN'), ('begin', 'NN'), ('and', 'CC'), ('end', 'NN'), (',', ','), ('and', 'CC'), ('thu